<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */

phutil_require_module('arcanist', 'configuration');
phutil_require_source('FacebookArcanistConfiguration.php');
