<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'FacebookArcanistConfiguration' => 'arcanist',
    'FacebookFbcodeUnitTestEngine' => 'unit/engine',
  ),
  'function' =>
  array(
    'get_conduit' => 'bin',
    'get_coverage_info' => 'bin',
    'get_diffid' => 'bin',
    'test' => 'bin',
    'update_buildstatus' => 'bin',
    'update_unitresults' => 'bin',
  ),
  'requires_class' =>
  array(
    'FacebookArcanistConfiguration' => 'ArcanistConfiguration',
    'FacebookFbcodeUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
  ),
  'requires_interface' =>
  array(
  ),
));
