<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('arcanist', 'exception/usage');
phutil_require_module('arcanist', 'exception/usage/noeffect');
phutil_require_module('arcanist', 'unit/engine/base');
phutil_require_module('arcanist', 'unit/result');

phutil_require_module('phutil', 'future');
phutil_require_module('phutil', 'future/exec');


phutil_require_source('FacebookFbcodeUnitTestEngine.php');
